name: dank_services_home
version: "0.0.1"
description: dank.services website
author: Harry Stern <harry@harrystern.net>
homepage: https://github.com/boustrophedon/dank.services
environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
    build_runner: ^1.1.2
    build_web_compilers: ^1.0.0
